services:
  app:
    build: .
    image: my_app
    environment:
      - "SPRING_PROFILES_ACTIVE=app"
      - SPRING_PORT=3000
    env_file:
      - .env
    ports:
      - '3000:3000'

  message-broker-app:
    build: .
    image: my_app
    environment:
      - "SPRING_PROFILES_ACTIVE=broker"
      - SPRING_PORT=3001
    ports:
      - '3001:3001'
    expose:
      - "3001"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local